name: cv-prince
channels:
    - conda-forge
dependencies:
    - python==3.10
    - pip==24.2
    - numpy==1.26
    - matplotlib==3.9.2
    - jupyter==1.0
    - opencv==4.10
    - pillow==11.0
    - scikit-learn==1.5
    - scikit-image==0.24
    - scipy==1.14
    - h5py==3.10
    - eventlet==0.37
    - flask-socketio==5.3
    - seaborn==0.13
    - pandas==1.5
    - imageio==2.36
    - sympy==1.13
    - pip:
        - moviepy==1.0
